export const GET_TEST_DATA_REQUEST = "GET_TEST_DATA_REQUEST";
export const GET_TEST_DATA_SUCCESS = "GET_TEST_DATA_SUCCESS";
export const GET_TEST_DATA_FAILURE = "GET_TEST_DATA_FAILURE";

export const SUBMIT_ANSWERS_REQUEST = "SUBMIT_ANSWERS_REQUEST";
export const SUBMIT_ANSWERS_SUCCESS = "SUBMIT_ANSWERS_SUCCESS";
export const SUBMIT_ANSWERS_FAILURE = "SUBMIT_ANSWERS_FAILURE";

export const GET_SUBJECTS_REQUEST = "GET_SUBJECTS_REQUEST";
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";
export const GET_SUBJECTS_FAILURE = "GET_SUBJECTS_FAILURE";

export const GET_SUBJECT_OF_TOPIC_REQUEST = "GET_SUBJECT_OF_TOPIC_REQUEST";
export const GET_SUBJECT_OF_TOPIC_SUCCESS = "GET_SUBJECT_OF_TOPIC_SUCCESS";
export const GET_SUBJECT_OF_TOPIC_FAILURE = "GET_SUBJECT_OF_TOPIC_FAILURE";

export const GET_TOPIC_OF_SUBJECT_REQUEST = "GET_TOPIC_OF_SUBJECT_REQUEST";
export const GET_TOPIC_OF_SUBJECT_SUCCESS = "GET_TOPIC_OF_SUBJECT_SUCCESS";
export const GET_TOPIC_OF_SUBJECT_FAILURE = "GET_TOPIC_OF_SUBJECT_FAILURE";

export const SUBMIT_TEST_REQUEST = "SUBMIT_TEST_REQUEST";
export const SUBMIT_TEST_SUCCESS = "SUBMIT_TEST_SUCCESS";
export const SUBMIT_TEST_FAILURE = "SUBMIT_TEST_FAILURE";

export const FETCH_UNLOCKED_LEVELS_REQUEST = "FETCH_UNLOCKED_LEVELS_REQUEST";
export const FETCH_UNLOCKED_LEVELS_SUCCESS = "FETCH_UNLOCKED_LEVELS_SUCCESS";
export const FETCH_UNLOCKED_LEVELS_FAILURE = "FETCH_UNLOCKED_LEVELS_FAILURE";
